// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mcp.server.enabled": boolean;
      "mcp.server.port": number;
      "general.fetchPDF": boolean;
      "general.defaultSort": string;
      "general.maxResults": number;
      "general.logLevel": string;
      "api.wos.key": string;
      "api.pubmed.key": string;
      "api.crossref.mailto": string;
      "api.semanticScholar.key": string;
      "api.elsevier.key": string;
      "platform.arxiv.enabled": boolean;
      "platform.arxiv.defaultSort": string;
      "platform.arxiv.maxResults": number;
      "platform.arxiv.sortOrder": string;
      "platform.crossref.enabled": boolean;
      "platform.crossref.defaultSort": string;
      "platform.crossref.maxResults": number;
      "platform.pubmed.enabled": boolean;
      "platform.pubmed.defaultSort": string;
      "platform.pubmed.maxResults": number;
      "platform.wos.enabled": boolean;
      "platform.wos.defaultSort": string;
      "platform.wos.maxResults": number;
      "platform.wos.database": string;
      "platform.zjusummon.enabled": boolean;
      "platform.zjusummon.defaultSort": string;
      "platform.zjusummon.maxResults": number;
      "platform.cqvip.enabled": boolean;
      "platform.cqvip.defaultSort": string;
      "platform.cqvip.maxResults": number;
      "platform.semantic.enabled": boolean;
      "platform.semantic.defaultSort": string;
      "platform.semantic.maxResults": number;
      "platform.scopus.enabled": boolean;
      "platform.scopus.defaultSort": string;
      "platform.scopus.maxResults": number;
      "platform.biorxiv.enabled": boolean;
      "platform.biorxiv.defaultSort": string;
      "platform.biorxiv.maxResults": number;
      "platform.medrxiv.enabled": boolean;
      "platform.medrxiv.defaultSort": string;
      "platform.medrxiv.maxResults": number;
      "web.mysearch.baseUrl": string;
      "web.mysearch.apiKey": string;
      "web.mysearch.mcpPath": string;
      "web.mysearch.proxyFirst": boolean;
      "web.tavily.apiKey": string;
      "web.tavily.baseUrl": string;
      "web.tavily.authMode": string;
      "web.tavily.searchPath": string;
      "web.tavily.extractPath": string;
      "web.firecrawl.apiKey": string;
      "web.firecrawl.baseUrl": string;
      "web.firecrawl.searchPath": string;
      "web.firecrawl.scrapePath": string;
      "web.exa.apiKey": string;
      "web.exa.baseUrl": string;
      "web.exa.searchPath": string;
      "web.xai.apiKey": string;
      "web.xai.baseUrl": string;
      "web.xai.model": string;
      "web.xai.searchMode": string;
      "web.xai.responsesPath": string;
      "web.xai.socialBaseUrl": string;
      "web.xai.socialSearchPath": string;
    };
  }
}
