// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "providers.registryUrl": string;
      "mcp.server.enabled": boolean;
      "mcp.server.port": number;
      "general.fetchPDF": boolean;
      "general.defaultSort": string;
      "general.maxResults": number;
      "general.logLevel": string;
      "general.probeQueryAcademic": string;
      "general.probeQueryPatent": string;
      "general.probeQueryWeb": string;
      "api.wos.key": string;
      "api.pubmed.key": string;
      "api.crossref.mailto": string;
      "api.semanticScholar.key": string;
      "api.elsevier.key": string;
      "web.mysearch.enabled": boolean;
      "web.mysearch.baseUrl": string;
      "web.mysearch.apiKey": string;
      "web.mysearch.mcpPath": string;
      "web.mysearch.proxyFirst": boolean;
      "web.tavily.enabled": boolean;
      "web.tavily.apiKey": string;
      "web.tavily.baseUrl": string;
      "web.tavily.authMode": string;
      "web.tavily.searchPath": string;
      "web.tavily.extractPath": string;
      "web.firecrawl.enabled": boolean;
      "web.firecrawl.apiKey": string;
      "web.firecrawl.baseUrl": string;
      "web.firecrawl.searchPath": string;
      "web.firecrawl.scrapePath": string;
      "web.exa.enabled": boolean;
      "web.exa.apiKey": string;
      "web.exa.baseUrl": string;
      "web.exa.searchPath": string;
      "web.xai.enabled": boolean;
      "web.xai.apiKey": string;
      "web.xai.baseUrl": string;
      "web.xai.model": string;
      "web.xai.searchMode": string;
      "web.xai.responsesPath": string;
      "web.xai.socialBaseUrl": string;
      "web.xai.socialSearchPath": string;
    };
  }
}
